config/routes.rb
Rails.application.routes.draw do
  
  root to: 'static_pages#index'

  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/electro_mech', to: 'static_pages#electro_mech', as: 'electro_mech'
  get '/servo', to: 'static_pages#servo', as: 'servo'
  get '/vfd', to: 'static_pages#vfd', as: 'vfd'
  get '/motors', to: 'static_pages#motors', as: 'motors'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    render :index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper

	def action_active?(*action_names)
		action_names.each{|an| return "active" if params[:action] == an}
		nil
	end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <meta content="text/html;charset=utf-8" http-equiv="Content-Type">
  <%= display_meta_tags site: 'Farrar Inc. ' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="//www.google-analytics.com/analytics.js" async=""></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>
  <link href='https://fonts.googleapis.com/css?family=Istok+Web:400,700,400italic' rel='stylesheet' type='text/css'>
  
  <!-- jQuery fallback !-->
  <script>
    if (typeof jQuery === 'undefined') {
      document.write(unescape('%3Cscript%20src%3D%22%2Fassets%2Fjquery-3.0.0.min.js%22%3E%3C%2Fscript%3E'));
    }
  </script>
</head>

<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="nav navbar-header">
      <a class="navbar-brand" href="<%= root_url %>">
        <div class="logof">
          <%= image_tag("farrar-logo-sm.png") %>
        </div>
        <div class="nav-slant">
        </div>
      </a>
      <!-- <ul class="navbar-left"> -->
      <!-- </ul> -->
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
      <div class="nav-buffer"></div>
      <ul class="nav navbar-nav">
        <li class="dropdown head">
          <a href="#" class="dropdown-toggle <%= action_active?("electro_mech", "vfd", "servo") %>" data-toggle="dropdown" role="button" aria-haspopup="true" >SERVICES</a>
          <ul class="dropdown-menu">
            <li><a href="<%= electro_mech_url %>">Electro/Mechanical Services</a></li>
            <li><a href="<%= servo_url %>">Servo Motor Repairs</a></li>
          </ul>
        </li>
        <li class="dropdown head">
          <a href="#" class="dropdown-toggle <%= action_active?("motors") %>" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">SALES</a>
          <ul class="dropdown-menu">
            <li><a href="<%= motors_url %>">Electric Motors</a></li>
            <li><a href="<%= vfd_url %>">Variable Frequency Drives</a></li>
          </ul>
        </li>
        <li class="head <%= action_active? "about" %>"><a href="<%= about_url %>">ABOUT US</a></li>
        <li class="head <%= action_active? "contact" %>"><a href="<%= contact_url %>">CONTACT</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <div class="nav navbar-right">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
  </div><!-- /.container-fluid -->
</nav>

<div class="clip-nav-wrapper visible-md-block visible-lg-block">
  <div class="clip-nav-box">
    <span class="call-now">24-hr Rush Service - Call <font style="font-size: 12pt;color: #f6cc7c;">866.708.1089</font></span>
  </div>
<div class="clip-nav-buffer"></div>
  <div class="clip-nav">
    <%= image_tag "clip-nav.png" %>
  </div>
</div>

<div class="bg-wrapper">
<div class="bg home"></div>
</div>

<div class="container">

<%= yield %>

</div>
<div class="linedivider-2"></div>
<div class="footer-wrapper">
<div class="footer">
  <div class="bg-wrapper">
    <div class="bg"></div>
    </div>
  <div class="container">
  <div class="row">
  <br>
  <br>
  <br>
  <div class="footer-text">
    <p>
    © 2016 Farrar Inc., Electric Motor Repair & Rewinding
    </p>
    <p>
Electro/Mechanical Services <span class="diamond">&#9670;</span> Rewinding <span class="diamond">&#9670;</span> Pumps <span class="diamond">&#9670;</span> Gearboxes <span class="diamond">&#9670;</span> Generators <span class="diamond">&#9670;</span> Servo Motor Services <span class="diamond">&#9670;</span> Variable Frequency Drives
</p>
We service the following Areas - New Hampshire, Massachusetts, Vermont, Maine, Connecticut, New York
  </p>
  </div>
  
  <div class="footer-text">

  </div>
  <div class="credit-cards">
    <%= image_tag("creditcardlogos.png", alt: "Visa, Mastercard, American Express, Discover") %>
  </div>
</div>
</div>
</div>
</div>

</body>
</html>

app/views/static_pages/about.html.erb
<div class="col-md-1"></div>
<div class="col-md-10 about center-white">

  <div class="banner">
  </div>
  <div class="clip">
    <%= image_tag("clip.png") %>
  </div>
  <div class="banner-h1">
    <h1>&nbsp;&nbsp;&nbsp;<%= title "About Us" %></h1>
  </div>
  <br/>
  <br/>
  <br/>
  <br/>
  <p>Frederick A. Farrar, Inc. was founded in 1937 as an electric motor repair shop by Frederick A. Farrar, an electrical engineer. In 1948, the growing business moved to its 15 Avon St. location.</p>

  <p>In 1958, Robert Farrar, also an electrical engineer, left Westinghouse Electric and joined his father in the firm. In 1983, Matthew Farrar, joined his father and grandfather in the company to enable this unique organization to continue in the family.</p>

  <div class="row">
    <div class="col-md-6">
    <%= image_tag("ABOUT US.JPG", class: "about-img", alt: "Electrical engineer in front of main address location") %>
    </div>

    <div class="col-md-6">
      <p>Today, the company has grown and expanded, directing its efforts to the industrial, water treatment, health care and construction markets of New England. The service department has worked on a broad spectrum of electric motors, ranging from small high-frequency to large synchronous units and a distribution team handles sales of electrical apparatus, motors, variable frequency drives and controls.</p>
      <br/>
      <p>Call us today at <font style="color: rgb(52, 87, 135);">866.708.1089</font> or Email your requirements.</p>

      <br/>
      <br/>
      <div class="yrs80">
        <%= image_tag("yrs80.jpg") %>
      </div>
    </div>

  </div>
  <br/>
  <h3>Certifications</h3>
  <div class="certifications">
    <div class="certifications-wrapper">
      <%= image_tag("certifications.jpg", class: "first", alt: "U.s. Department of Labor MSHA Mine Safety & Health Administration") %>
      <%= image_tag("certifications2.jpg", alt: "OSHA 10 hour") %>
      <%= image_tag("certifications3.jpg", class: "easa", alt: "EASA Electrical Apparatus Service Association") %>
      <%= image_tag("certifications4.jpg", class: "last", alt: "Flygt Pumps") %>
    </div>
  </div>
  <br/>
  <br/>
  <br/>
</div>
<div class="col-md-1"></div>

app/views/static_pages/contact.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 center-white">

		<div class="banner">
		</div>
		<div class="clip">
	    	<%= image_tag("clip.png") %>
		</div>
		<div class="banner-h1">
	    	<h1>&nbsp;&nbsp;&nbsp;<%= title "Contact Us" %></h1>
		</div>
		<br/>
		<br/>
		<br/>
		<br/>
		<div class="contact-us-left">
			<p>24-Hour Service
			</p>

			<p><b>Farrar Inc.</b>
			<br/>15 Avon St.
			<br/>Keene, NH 03431-3596</p>
			<br/>
			<div class="contact-us-email">
				For general questions, email:
				<br/>
				<h3>info@fafarrar.com</h3>
			</div>
			<br/>
			<br/>
		</div>
		<div class="contact-us-right">
			<p>Telephone: 603-352-4316</p>
			<p>Toll Free: 866-708-1089</p>
			<p>Fax: 603-357-9476</p>
		</div>
		<div class="contact-image">
			<%= image_tag("FIELD SERVICE1.jpg", alt: "New Hampshire Truck and Delivery Services") %>
		</div>
	</div>
	<div class="col-md-1"></div>

</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 directions-wrapper">
		<div class="banner directions-banner dark-blue-grad">
		  </div>
		  <div class="banner-h1">
		    <h1 id="brands">&nbsp;&nbsp;&nbsp;Directions</h1>
		  </div>
		  <br/>
		  <br/>
		<div class="map" style="margin:0px;padding:0px;overflow:hidden">
			<iframe style="overflow:hidden;height:600px;width:100%" height="600" width="100%"
			  frameborder="0" style="border:0"
			  src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.secrets.google_maps_key %>&q=Frederick+A+Farrar+Inc" allowfullscreen>
			</iframe>
		</div>
	</div>
	<div class="col-md-1"></div>
</div>
<br/>
<div class="row">

	<div class="col-md-1"></div>
	<div class="col-md-10 center-white line-cards-wrapper-bg">
		<div class="sliver"></div>
	<div class="line-cards-wrapper">
		<br/><h3>Line Cards</h3>
		<div class="line-cards">
		<script language="javascript" type="text/javascript">
            function printImage(urlstr) {
                var win = window.open(urlstr, "_blank");
				win.onload = function() { win.print(); }
            }
       </script>
			<br/>
		 	<%= link_to "Electro Mechanical Services", image_path("linecard-ems.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-ems.jpg") %>')">PRINT</a>
		 	<br/>
			<%= link_to "Energy Efficient Motors", image_path("linecard-eem.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-eem.jpg") %>')">PRINT</a>
			<br/>
			<%= link_to "Servo Motors", image_path("linecard-smr.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-smr.jpg") %>')">PRINT</a>
			<br/>
			<%= link_to "Motor/Pump Repair", image_path("linecard-mpr.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-mpr.jpg") %>')">PRINT</a>
			<br/>
			<%= link_to "Pump Services", image_path("linecard-ps.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-ps.jpg") %>')">PRINT</a>
			<br/>
			<%= link_to "Field Services", image_path("linecard-fs.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-fs.jpg") %>')">PRINT</a>
			<br/>
			<%= link_to "VFD Brands Available", image_path("linecard-vfd.jpg") %>
			<a href="#" class= "print" onclick="printImage('<%= image_path("linecard-vfd.jpg") %>')">PRINT</a>

			<br/>
			<br/>
			<br/>
		</div>
	</div>
	</div>
	<div class="col-md-1"></div>

</div>

app/views/static_pages/index.html.erb
<%# description 'Frederick A Farrar, Inc. electric/mechanical services, motor distribution and motor repair' %>
<% description 'totallyuniquestring descriptionstring' %>
<div class="row">

  <div class="heading">
  <h3 class="heading">
  Committed to serving you promptly, efficiently and honestly.
  </h3>
  </div>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
      <li data-target="#myCarousel" data-slide-to="4"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <%= image_tag( "HOME 3.jpg", alt: "Delivery and moving services for large motors and motor parts") %>
      </div>

      <div class="item">
        <%= image_tag("HOME 2.jpg", alt: "75 years of Excellence in the repair shop") %>
      </div>

      <div class="item">
        <%= image_tag("HOME 1.jpg", alt: "Scheduled professional motor inspection") %>
      </div>

      <div class="item">
        <%= image_tag("HOME 4.jpg", alt: "Konecranes mechanical equipment") %>
      </div>

      <div class="item">
        <%= image_tag("HOME 5.jpg", alt: "Electric motor warehouse for testing motors and drives") %>
      </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 center-white home">
      <div class="banner dark-blue-grad">
      </div>
      <div class="clip dark-blue">
        <%= image_tag("clip-light.png") %>
      </div>
      <div class="banner-h1">
        <h1>&nbsp;&nbsp;&nbsp;<%= title "Home" %></h1>
      </div>
      <br/>
      <br/>
      <br/>
      <br/>
      <p>
         At Farrar, you will find that we work with our valued customers to beat deadlines, locate the causes of machinery failure, complete emergency motor repairs, and keep motors in top operating condition to prevent breakdowns. But, most importantly, all of us at FARRAR, Inc. share a commitment to serving you promptly, efficiently and honestly.
      </p>
      <p>I invite you to call Matt Farrar, President, toll-free at 866.708.1089 or email him with any questions or problems you have concerning servo motor repair, electric motor repair, variable frequency drives, pumps, generators or electro-mechanical equipment.
      </p>
      <br/>
      <div class="easa-wrapper">
      <ul>
  <%= image_tag("easa.jpg", alt: "Member EASA, The Electro-Mechanical Authority") %>
  <li><font style="color: black;">AC Servo Motor Repairs &amp; DC Servo Motor Repairs, (including those fitted to robots and machine tools)</font></li><li><font style="color: black;">

  Absolute &amp; Linear Encoder Servo Repairs</font></li>

  <li><font style="color: black;">
  Electrical Mechanical Apparatus Services</font></li>

  <li><font style="color: black;">
  AC &amp; DC New Motor Replacement</font></li>
  <li><font style="color: black;">Pump Repair</font></li>
  <li><font style="color: black;">
  Water/Chemical/Vacuum</font></li>
  <li><font style="color: black;">
  Generator Maintenance & Repair</font></li>
  <li><font style="color: black;">
  Motor Controls, Variable Frequency Drives, Reduced Voltage Starters</font></li>
  <li><font style="color: black;">
  Controls Engineering, Panel Fabrication, Design and Construction</font></li>
  <li><font style="color: black;">
  Electric Motors: Baldor, General Electric, A. O. Smith, Siemens, 
  Worldwide (Hyundai), Fasco, U.S. Motors, and many others!</font></li>
  <li><font style="color: black;">
  AC Drives: Yaskawa, Danfoss, Toshiba, Teco, Westinghouse</font></li>
  <li><font style="color: black;">
  DC Drives: Baldor</font></li>
  <li><font style="color: black;">Pro-Active Maintenance Services and Comprehensive Total Maintenance Packages</font></li>
  <span style="color: black; ">
  <li><font style="color: black;">Site Teams for Electrical and Mechanical Equipment Removal and Re-installation</font></li>
  <li><font style="color: black;">Infra-Red Scanning</font></li>
  <li><font style="color: black;">Powder Coating For Corrosive Environments</font></li>
  <li><font style="color: black;">Flygt Pumps Service Center</font></li>
  </span></ul>


  </div>
  <br/>
  <br/>



    </div>
    <div class="col-md-1"></div>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10 center-white line-cards-wrapper-bg home">
      <div class="sliver"></div>
      <div class="line-cards-wrapper home">
        <div class="home-item servicec">
          <h2>Service Center</h2>

          <a href="<%= electro_mech_url %>">Electro/Mechanical Services</a><br/>
          <a href="<%= vfd_url %>">Variable Frequency Drives</a><br/>
          <a href="#">Motor Rewinding</a><br/>
          <a href="<%= servo_url %>">Servo Motor Repairs</a><br/>
          <a href="#">Pump Rebuilds</a><br/>
          <a href="#">Gearbox Rebuilds</a><br/>
        </div>
        <div class="home-item salesc">
          <h2>Sales Center</h2>

          <a href="<%= motors_url %>">Electric Motors</a><br>
          <a href="<%= vfd_url %>">Variable Frequency Drives</a><br>
          <a href="#">Pumps</a><br>
          <a href="#">Gearboxes</a><br>
        </div>
        <div class="home-item im">
          <%= image_tag("FIELD SERVICE3.jpg", alt: "rookie on the job") %>
        </div>
      </div>

    </div>

    <div class="col-md-1"></div>

  </div>
</div>

app/views/static_pages/motors.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-2 sidebox">

		<div class="ems-images">
			<br/><%= image_tag("ELECTRIC MOTOR.JPG", alt: "Electric motor parts with repair shop truck loading") %>
			<br/><br/><%= image_tag("ELECTRIC MOTOR1.jpg", alt: "On-site rush services for electric motor maintenance") %>
			<br/><br/>
		</div>
	
	</div>
	<div class="col-md-8 center-white">		
		<h2 class="motors"><%= title "Electric Motors" %></h2>


		<p>Through the years, FARRAR, Inc. has brought together a high-quality mix of product lines, which has created a diversified, yet complementary system of equipment and parts to serve all your electro-mechanical needs. Our staff is ready to deliver on-time and competitive quotes and to provide exceptional service after the sale for all of the high quality manufacturer’s lines we carry, including the industry’s broadest line of energy-efficient electric motors and adjustable speed drives.</p>

		<p>
		Our motor repair and rewinding shop is state-of-the-art and features a fully-stocked parts inventory to provide quick turnaround on your most critical repairs. All work is performed by trained technicians who are supported by a fully-equipped service fleet available 24-hours-a-day, 7-days-a-week to handle any emergency.</p>
		<br/>
		<br/>
		<br/><br/><br/><br/><br/><br/><br/><br/>
	</div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 center-white vfd">
		<div class="banner vfd dark-blue-grad">
		  </div>
		  <div class="clip dark-blue">
		    <%= image_tag("clip-light.png") %>
		  </div>
		  <div class="banner-h1">
		    <h1 id="brands">&nbsp;&nbsp;&nbsp;Electric Motor Brands</h1>
		  </div>
		  <br/>
		  <br/>
		  <br/>
		  <br/>
		  <p>Fractional through 10,000+ horse power (AC / DC)</p>
		  <br/>
		  <div class="motor-brands-wrapper">
		  <table class="motor-brands">
		  	<tbody>
			  <tr>
			  	<td><%= image_tag("brand-1.jpg") %>
			  	</td>
			  	<td class="text">Baldor
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-2.jpg") %>
			  	</td>
			  	<td class="text">General Electric
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-3.jpg") %>
			  	</td>
			  	<td class="text">A.O. Smith
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-4.jpg") %>
			  	</td>
			  	<td class="text">Siemens
			  	</td>
			  </tr>
		    </tbody>
		  </table>
		  <table class="motor-brands">
			<tbody>  
			  <tr>
			  	<td><%= image_tag("brand-6.jpg") %>
			  	</td>
			  	<td class="text">Fasco
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-5.jpg") %>
			  	</td>
			  	<td class="text">WorldWide
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-7.jpg") %>
			  	</td>
			  	<td class="text">Marathon
			  	</td>
			  </tr>
			  <tr>
			  	<td><%= image_tag("brand-8.gif") %>
			  	</td>
			  	<td class="text">Teco-Westinghouse
			  	</td>
			  </tr>
			</tbody>
		  </table>
		  </div>
		  <br/>
		  <br/>
	</div>
	<div class="col-md-1"></div>
</div>

app/views/static_pages/vfd.html.erb
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-2 sidebox">

		<div class="ems-images">
			<br/><%= image_tag("VFD.JPG", alt: "Varible Frequency Drives assistance with HVAC") %><br/><br/>
			<br/><%= image_tag("VFD2.jpg", alt: "VFD integration support, help and services") %><br/><br/>
			<br/><%= image_tag("VFD3.jpg", alt: "VFD checkup and monitoring") %><br/><br/>
		</div>
	
	</div>
	<div class="col-md-8 center-white">		
		<h2><%= title "VFD Assistance" %></h2>


		<p> With variable-frequency drives (VFD) getting smaller and less expensive, their use in HVAC systems to control air-handler fans, cooling tower fans, and pumps for both heating and cooling systems, has been rapidly growing.  It is important, however, to remember that VFDs only save energy if they are properly controlled and integrated into building-automation systems. Integration issues, including network protocols, hardware connections, and trending all need to be considered during the design phase.</p>

		<p>Farrar can offer a full range of VFD products and services, from project concept and full turn-key design and coordination to start-up, including engineering, programming and  documentation. Farrar also applies its long-time motor repair commitment to following common sense logic and employing state-of-the-art tools and equipment to its repair of variable frequency drives.</p>

		<p>Farrar troubleshoots the applications, from wiring to loads, before looking at drives themselves, which saves you time and money!</p>
		

		<p>
			<span class="vfd-list">Industrial AC &amp; DC Drives</span><br/>
			Adjustable Frequency Drives
		</p>
		<p>
			<span class="vfd-list">Commercial HVAC Drives</span><br/>
			VFDs For Building Automation Systems
		</p>
		<p>
			<span class="vfd-list">Spindle Drives And Motors</span><br/>
			Designed For High-Speed Spindles
		</p>
		<p>
			<span class="vfd-list">Servo Systems And Motor Controllers</span><br/>
			Repair and Sales of Brushless AC Servos, Digital Amplifiers, Linear Motors, Direct Drive Motors and Servo Gear Motors
		</p>
		<p>
			<span class="vfd-list">Low Voltage Industrial Controls</span><br/>
			Reduced Voltage Starters, Elements, Relays, Proximity Sensors, Push-Buttons, and Other Control Devices
		</p>

			<br/><br/><br/><br/>
	</div>
	<div class="col-md-1"></div>
</div>
<div class="row">
	<div class="col-md-1"></div>
	<div class="col-md-10 center-white vfd">
		<div class="banner vfd dark-blue-grad">
		  </div>
		  <div class="clip dark-blue">
		    <%= image_tag("clip-light.png") %>
		  </div>
		  <div class="banner-h1">
		    <h1 id="brands">&nbsp;&nbsp;&nbsp;VFD Brands Available</h1>
		  </div>
		  <br/>
		  <br/>
		  <br/>
		  <br/>
		  <p>Contact <a href="<%= contact_url %>">Inside Sales</a> about our selection of Variable Frequency Drives, Spindle Drives &amp; Motors, AC Drives - HVAC Drives and DC Drives.</p>
		  <br/>
		  <div class="vfd-imgs">
			  <div class="vfd-img yask">
				  <%= image_tag("vfd-2.png") %>
				  <div class="vfd-span"><span>HVAC</span></div>
			  </div>
			  <div class="vfd-img">
				  <%= image_tag("vfd-3.png") %>
				  <div class="vfd-span"><span>Industrial</span></div>
			  </div>
			  <div class="vfd-img">
				  <%= image_tag("vfd-4.png") %>
			  	  <div class="vfd-span"><span>Water/Waste Water</span></div>
			  </div>
			  <div class="vfd-img">
				  <%= image_tag("vfd-5.png") %>
			  	  <div class="vfd-span"><span>Harmonic Filter Solutions</span></div>
			  </div>
			  <br/>
		  </div>
		  <ul class="vfd">
			  <li><font style="color: black;">Quick Quotation Turnaround</font></li>
			  <li><font style="color: black;">Expert Engineering Support</font></li>
			  <li><font style="color: black;">Certified Start-up</font></li>
			  <li><font style="color: black;">HVAC Systems</font></li>
			  <li><font style="color: black;">Energy Retrofits</font></li>
			  <li><font style="color: black;">Design/Build Projects</font></li>
			  <li><font style="color: black;">Payback Analysis</font></li>
			  <li><font style="color: black;">Configured Drives</font></li>
			  <li><font style="color: black;">Preventative Maintenance</font></li>
			  <li><font style="color: black;">Energy Efficient Motors</font></li>
			  <li><font style="color: black;">IEEE Harmonic Analysis</font></li>
		  </ul>
		  <br/>
		  <div class="line-cards">
			&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to "Download Line Card", "/assets/pdfs/vfd.pdf" %>
		  </div>
		  <br/>
		  <br/>
		  <br/>
		  <br/>
		  <br/>
		  <br/>
	</div>
	<div class="col-md-1"></div>
</div>